<?php
/**
 * CategoriesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * finAPI RESTful Services
 *
 * finAPI RESTful Services
 *
 * OpenAPI spec version: v1.81.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * CategoriesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CategoriesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createCategory
     *
     * Create a new category.
     *
     */
    public function testCreateCategory()
    {
    }

    /**
     * Test case for deleteAllCategories
     *
     * Delete all categories.
     *
     */
    public function testDeleteAllCategories()
    {
    }

    /**
     * Test case for deleteCategory
     *
     * Delete a category.
     *
     */
    public function testDeleteCategory()
    {
    }

    /**
     * Test case for editCategory
     *
     * Edit a category.
     *
     */
    public function testEditCategory()
    {
    }

    /**
     * Test case for getAndSearchAllCategories
     *
     * Get and search all categories.
     *
     */
    public function testGetAndSearchAllCategories()
    {
    }

    /**
     * Test case for getCashFlows
     *
     * Get cash flows.
     *
     */
    public function testGetCashFlows()
    {
    }

    /**
     * Test case for getCategory
     *
     * Get a category.
     *
     */
    public function testGetCategory()
    {
    }

    /**
     * Test case for getMultipleCategories
     *
     * Get multiple categories.
     *
     */
    public function testGetMultipleCategories()
    {
    }

    /**
     * Test case for trainCategorization
     *
     * Train categorization.
     *
     */
    public function testTrainCategorization()
    {
    }
}
