<?php
/**
 * LabelsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * finAPI RESTful Services
 *
 * finAPI RESTful Services
 *
 * OpenAPI spec version: v1.81.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * LabelsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class LabelsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createLabel
     *
     * Create a new label.
     *
     */
    public function testCreateLabel()
    {
    }

    /**
     * Test case for deleteAllLabels
     *
     * Delete all labels.
     *
     */
    public function testDeleteAllLabels()
    {
    }

    /**
     * Test case for deleteLabel
     *
     * Delete a label.
     *
     */
    public function testDeleteLabel()
    {
    }

    /**
     * Test case for editLabel
     *
     * Edit a label.
     *
     */
    public function testEditLabel()
    {
    }

    /**
     * Test case for getAndSearchAllLabels
     *
     * Get and search all labels.
     *
     */
    public function testGetAndSearchAllLabels()
    {
    }

    /**
     * Test case for getLabel
     *
     * Get a label.
     *
     */
    public function testGetLabel()
    {
    }

    /**
     * Test case for getMultipleLabels
     *
     * Get multiple labels.
     *
     */
    public function testGetMultipleLabels()
    {
    }
}
