<?php
/**
 * MandatorAdministrationApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * finAPI RESTful Services
 *
 * finAPI RESTful Services
 *
 * OpenAPI spec version: v1.81.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * MandatorAdministrationApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MandatorAdministrationApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for changeClientCredentials
     *
     * Change client credentials.
     *
     */
    public function testChangeClientCredentials()
    {
    }

    /**
     * Test case for createIbanRules
     *
     * Create IBAN rules.
     *
     */
    public function testCreateIbanRules()
    {
    }

    /**
     * Test case for createKeywordRules
     *
     * Create keyword rules.
     *
     */
    public function testCreateKeywordRules()
    {
    }

    /**
     * Test case for deleteIbanRules
     *
     * Delete IBAN rules.
     *
     */
    public function testDeleteIbanRules()
    {
    }

    /**
     * Test case for deleteKeywordRules
     *
     * Delete keyword rules.
     *
     */
    public function testDeleteKeywordRules()
    {
    }

    /**
     * Test case for deleteUsers
     *
     * Delete users.
     *
     */
    public function testDeleteUsers()
    {
    }

    /**
     * Test case for getIbanRuleList
     *
     * Get IBAN rules.
     *
     */
    public function testGetIbanRuleList()
    {
    }

    /**
     * Test case for getKeywordRuleList
     *
     * Get keyword rules.
     *
     */
    public function testGetKeywordRuleList()
    {
    }

    /**
     * Test case for getUserList
     *
     * Get user list.
     *
     */
    public function testGetUserList()
    {
    }
}
