<?php
/**
 * NotificationRulesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * finAPI RESTful Services
 *
 * finAPI RESTful Services
 *
 * OpenAPI spec version: v1.81.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * NotificationRulesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class NotificationRulesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createNotificationRule
     *
     * Create a new notification rule.
     *
     */
    public function testCreateNotificationRule()
    {
    }

    /**
     * Test case for deleteAllNotificationRules
     *
     * Delete all notification rules.
     *
     */
    public function testDeleteAllNotificationRules()
    {
    }

    /**
     * Test case for deleteNotificationRule
     *
     * Delete a notification rule.
     *
     */
    public function testDeleteNotificationRule()
    {
    }

    /**
     * Test case for getAndSearchAllNotificationRules
     *
     * Get and search all notification rules.
     *
     */
    public function testGetAndSearchAllNotificationRules()
    {
    }

    /**
     * Test case for getNotificationRule
     *
     * Get a notification rule.
     *
     */
    public function testGetNotificationRule()
    {
    }
}
