<?php
/**
 * AccountTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * finAPI RESTful Services
 *
 * finAPI RESTful Services
 *
 * OpenAPI spec version: v1.81.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * AccountTest Class Doc Comment
 *
 * @category    Class
 * @description Container for a bank account&#39;s data
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AccountTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Account"
     */
    public function testAccount()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "bank_connection_id"
     */
    public function testPropertyBankConnectionId()
    {
    }

    /**
     * Test attribute "account_name"
     */
    public function testPropertyAccountName()
    {
    }

    /**
     * Test attribute "iban"
     */
    public function testPropertyIban()
    {
    }

    /**
     * Test attribute "account_number"
     */
    public function testPropertyAccountNumber()
    {
    }

    /**
     * Test attribute "sub_account_number"
     */
    public function testPropertySubAccountNumber()
    {
    }

    /**
     * Test attribute "account_holder_name"
     */
    public function testPropertyAccountHolderName()
    {
    }

    /**
     * Test attribute "account_holder_id"
     */
    public function testPropertyAccountHolderId()
    {
    }

    /**
     * Test attribute "account_currency"
     */
    public function testPropertyAccountCurrency()
    {
    }

    /**
     * Test attribute "account_type_id"
     */
    public function testPropertyAccountTypeId()
    {
    }

    /**
     * Test attribute "account_type_name"
     */
    public function testPropertyAccountTypeName()
    {
    }

    /**
     * Test attribute "account_type"
     */
    public function testPropertyAccountType()
    {
    }

    /**
     * Test attribute "balance"
     */
    public function testPropertyBalance()
    {
    }

    /**
     * Test attribute "overdraft"
     */
    public function testPropertyOverdraft()
    {
    }

    /**
     * Test attribute "overdraft_limit"
     */
    public function testPropertyOverdraftLimit()
    {
    }

    /**
     * Test attribute "available_funds"
     */
    public function testPropertyAvailableFunds()
    {
    }

    /**
     * Test attribute "last_successful_update"
     */
    public function testPropertyLastSuccessfulUpdate()
    {
    }

    /**
     * Test attribute "last_update_attempt"
     */
    public function testPropertyLastUpdateAttempt()
    {
    }

    /**
     * Test attribute "is_new"
     */
    public function testPropertyIsNew()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "supported_orders"
     */
    public function testPropertySupportedOrders()
    {
    }

    /**
     * Test attribute "interfaces"
     */
    public function testPropertyInterfaces()
    {
    }

    /**
     * Test attribute "clearing_accounts"
     */
    public function testPropertyClearingAccounts()
    {
    }
}
