<?php
/**
 * ClientConfigurationParamsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * finAPI RESTful Services
 *
 * finAPI RESTful Services
 *
 * OpenAPI spec version: v1.81.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ClientConfigurationParamsTest Class Doc Comment
 *
 * @category    Class
 * @description Client configuration parameters
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ClientConfigurationParamsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ClientConfigurationParams"
     */
    public function testClientConfigurationParams()
    {
    }

    /**
     * Test attribute "user_notification_callback_url"
     */
    public function testPropertyUserNotificationCallbackUrl()
    {
    }

    /**
     * Test attribute "user_synchronization_callback_url"
     */
    public function testPropertyUserSynchronizationCallbackUrl()
    {
    }

    /**
     * Test attribute "refresh_tokens_validity_period"
     */
    public function testPropertyRefreshTokensValidityPeriod()
    {
    }

    /**
     * Test attribute "user_access_tokens_validity_period"
     */
    public function testPropertyUserAccessTokensValidityPeriod()
    {
    }

    /**
     * Test attribute "client_access_tokens_validity_period"
     */
    public function testPropertyClientAccessTokensValidityPeriod()
    {
    }

    /**
     * Test attribute "is_pin_storage_available_in_web_form"
     */
    public function testPropertyIsPinStorageAvailableInWebForm()
    {
    }

    /**
     * Test attribute "store_secrets_available_in_web_form"
     */
    public function testPropertyStoreSecretsAvailableInWebForm()
    {
    }

    /**
     * Test attribute "application_name"
     */
    public function testPropertyApplicationName()
    {
    }

    /**
     * Test attribute "fin_ts_product_registration_number"
     */
    public function testPropertyFinTsProductRegistrationNumber()
    {
    }
}
