<?php
/**
 * EditBankConnectionParamsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * finAPI RESTful Services
 *
 * finAPI RESTful Services
 *
 * OpenAPI spec version: v1.81.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * EditBankConnectionParamsTest Class Doc Comment
 *
 * @category    Class
 * @description Container for bank connection edit params
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EditBankConnectionParamsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "EditBankConnectionParams"
     */
    public function testEditBankConnectionParams()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "banking_user_id"
     */
    public function testPropertyBankingUserId()
    {
    }

    /**
     * Test attribute "banking_customer_id"
     */
    public function testPropertyBankingCustomerId()
    {
    }

    /**
     * Test attribute "banking_pin"
     */
    public function testPropertyBankingPin()
    {
    }

    /**
     * Test attribute "interface"
     */
    public function testPropertyInterface()
    {
    }

    /**
     * Test attribute "login_credentials"
     */
    public function testPropertyLoginCredentials()
    {
    }

    /**
     * Test attribute "default_two_step_procedure_id"
     */
    public function testPropertyDefaultTwoStepProcedureId()
    {
    }
}
