<?php
/**
 * MockBankConnectionUpdateTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * finAPI RESTful Services
 *
 * finAPI RESTful Services
 *
 * OpenAPI spec version: v1.81.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * MockBankConnectionUpdateTest Class Doc Comment
 *
 * @category    Class
 * @description Data for a mock bank connection update
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MockBankConnectionUpdateTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "MockBankConnectionUpdate"
     */
    public function testMockBankConnectionUpdate()
    {
    }

    /**
     * Test attribute "bank_connection_id"
     */
    public function testPropertyBankConnectionId()
    {
    }

    /**
     * Test attribute "interface"
     */
    public function testPropertyInterface()
    {
    }

    /**
     * Test attribute "simulate_bank_login_error"
     */
    public function testPropertySimulateBankLoginError()
    {
    }

    /**
     * Test attribute "mock_accounts_data"
     */
    public function testPropertyMockAccountsData()
    {
    }
}
