<?php
/**
 * MonthlyUserStatsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * finAPI RESTful Services
 *
 * finAPI RESTful Services
 *
 * OpenAPI spec version: v1.81.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * MonthlyUserStatsTest Class Doc Comment
 *
 * @category    Class
 * @description Information about a user&#39;s data or activities for a certain month
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MonthlyUserStatsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "MonthlyUserStats"
     */
    public function testMonthlyUserStats()
    {
    }

    /**
     * Test attribute "month"
     */
    public function testPropertyMonth()
    {
    }

    /**
     * Test attribute "min_bank_connection_count"
     */
    public function testPropertyMinBankConnectionCount()
    {
    }

    /**
     * Test attribute "max_bank_connection_count"
     */
    public function testPropertyMaxBankConnectionCount()
    {
    }
}
