<?php
/**
 * MultiStepAuthenticationChallengeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * finAPI RESTful Services
 *
 * finAPI RESTful Services
 *
 * OpenAPI spec version: v1.81.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * MultiStepAuthenticationChallengeTest Class Doc Comment
 *
 * @category    Class
 * @description Container for multi-step authentication data, as returned by finAPI to the client
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MultiStepAuthenticationChallengeTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "MultiStepAuthenticationChallenge"
     */
    public function testMultiStepAuthenticationChallenge()
    {
    }

    /**
     * Test attribute "hash"
     */
    public function testPropertyHash()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "challenge_message"
     */
    public function testPropertyChallengeMessage()
    {
    }

    /**
     * Test attribute "answer_field_label"
     */
    public function testPropertyAnswerFieldLabel()
    {
    }

    /**
     * Test attribute "redirect_url"
     */
    public function testPropertyRedirectUrl()
    {
    }

    /**
     * Test attribute "redirect_context"
     */
    public function testPropertyRedirectContext()
    {
    }

    /**
     * Test attribute "redirect_context_field"
     */
    public function testPropertyRedirectContextField()
    {
    }

    /**
     * Test attribute "two_step_procedures"
     */
    public function testPropertyTwoStepProcedures()
    {
    }

    /**
     * Test attribute "optical_data"
     */
    public function testPropertyOpticalData()
    {
    }

    /**
     * Test attribute "photo_tan_mime_type"
     */
    public function testPropertyPhotoTanMimeType()
    {
    }

    /**
     * Test attribute "photo_tan_data"
     */
    public function testPropertyPhotoTanData()
    {
    }
}
