<?php
/**
 * PageableTransactionListTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * finAPI RESTful Services
 *
 * finAPI RESTful Services
 *
 * OpenAPI spec version: v1.81.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * PageableTransactionListTest Class Doc Comment
 *
 * @category    Class
 * @description Container for a page of transactions, with data about the total count of transactions and their balance
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PageableTransactionListTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PageableTransactionList"
     */
    public function testPageableTransactionList()
    {
    }

    /**
     * Test attribute "transactions"
     */
    public function testPropertyTransactions()
    {
    }

    /**
     * Test attribute "paging"
     */
    public function testPropertyPaging()
    {
    }

    /**
     * Test attribute "income"
     */
    public function testPropertyIncome()
    {
    }

    /**
     * Test attribute "spending"
     */
    public function testPropertySpending()
    {
    }

    /**
     * Test attribute "balance"
     */
    public function testPropertyBalance()
    {
    }
}
