<?php
/**
 * RequestSepaDirectDebitParamsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * finAPI RESTful Services
 *
 * finAPI RESTful Services
 *
 * OpenAPI spec version: v1.81.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * RequestSepaDirectDebitParamsTest Class Doc Comment
 *
 * @category    Class
 * @description Parameters for a single or collective SEPA direct debit order request
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RequestSepaDirectDebitParamsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "RequestSepaDirectDebitParams"
     */
    public function testRequestSepaDirectDebitParams()
    {
    }

    /**
     * Test attribute "account_id"
     */
    public function testPropertyAccountId()
    {
    }

    /**
     * Test attribute "banking_pin"
     */
    public function testPropertyBankingPin()
    {
    }

    /**
     * Test attribute "store_secrets"
     */
    public function testPropertyStoreSecrets()
    {
    }

    /**
     * Test attribute "two_step_procedure_id"
     */
    public function testPropertyTwoStepProcedureId()
    {
    }

    /**
     * Test attribute "direct_debit_type"
     */
    public function testPropertyDirectDebitType()
    {
    }

    /**
     * Test attribute "sequence_type"
     */
    public function testPropertySequenceType()
    {
    }

    /**
     * Test attribute "execution_date"
     */
    public function testPropertyExecutionDate()
    {
    }

    /**
     * Test attribute "single_booking"
     */
    public function testPropertySingleBooking()
    {
    }

    /**
     * Test attribute "direct_debits"
     */
    public function testPropertyDirectDebits()
    {
    }

    /**
     * Test attribute "hide_transaction_details_in_web_form"
     */
    public function testPropertyHideTransactionDetailsInWebForm()
    {
    }

    /**
     * Test attribute "multi_step_authentication"
     */
    public function testPropertyMultiStepAuthentication()
    {
    }

    /**
     * Test attribute "store_pin"
     */
    public function testPropertyStorePin()
    {
    }
}
