<?php
/**
 * SecurityTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * finAPI RESTful Services
 *
 * finAPI RESTful Services
 *
 * OpenAPI spec version: v1.81.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * SecurityTest Class Doc Comment
 *
 * @category    Class
 * @description Container for a security position&#39;s data
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SecurityTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Security"
     */
    public function testSecurity()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "account_id"
     */
    public function testPropertyAccountId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "isin"
     */
    public function testPropertyIsin()
    {
    }

    /**
     * Test attribute "wkn"
     */
    public function testPropertyWkn()
    {
    }

    /**
     * Test attribute "quote"
     */
    public function testPropertyQuote()
    {
    }

    /**
     * Test attribute "quote_currency"
     */
    public function testPropertyQuoteCurrency()
    {
    }

    /**
     * Test attribute "quote_type"
     */
    public function testPropertyQuoteType()
    {
    }

    /**
     * Test attribute "quote_date"
     */
    public function testPropertyQuoteDate()
    {
    }

    /**
     * Test attribute "quantity_nominal"
     */
    public function testPropertyQuantityNominal()
    {
    }

    /**
     * Test attribute "quantity_nominal_type"
     */
    public function testPropertyQuantityNominalType()
    {
    }

    /**
     * Test attribute "market_value"
     */
    public function testPropertyMarketValue()
    {
    }

    /**
     * Test attribute "market_value_currency"
     */
    public function testPropertyMarketValueCurrency()
    {
    }

    /**
     * Test attribute "entry_quote"
     */
    public function testPropertyEntryQuote()
    {
    }

    /**
     * Test attribute "entry_quote_currency"
     */
    public function testPropertyEntryQuoteCurrency()
    {
    }

    /**
     * Test attribute "profit_or_loss"
     */
    public function testPropertyProfitOrLoss()
    {
    }
}
