<?php
/**
 * TransactionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * finAPI RESTful Services
 *
 * finAPI RESTful Services
 *
 * OpenAPI spec version: v1.81.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * TransactionTest Class Doc Comment
 *
 * @category    Class
 * @description Container for a transaction&#39;s data
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TransactionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Transaction"
     */
    public function testTransaction()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "parent_id"
     */
    public function testPropertyParentId()
    {
    }

    /**
     * Test attribute "account_id"
     */
    public function testPropertyAccountId()
    {
    }

    /**
     * Test attribute "value_date"
     */
    public function testPropertyValueDate()
    {
    }

    /**
     * Test attribute "bank_booking_date"
     */
    public function testPropertyBankBookingDate()
    {
    }

    /**
     * Test attribute "finapi_booking_date"
     */
    public function testPropertyFinapiBookingDate()
    {
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
    }

    /**
     * Test attribute "purpose"
     */
    public function testPropertyPurpose()
    {
    }

    /**
     * Test attribute "counterpart_name"
     */
    public function testPropertyCounterpartName()
    {
    }

    /**
     * Test attribute "counterpart_account_number"
     */
    public function testPropertyCounterpartAccountNumber()
    {
    }

    /**
     * Test attribute "counterpart_iban"
     */
    public function testPropertyCounterpartIban()
    {
    }

    /**
     * Test attribute "counterpart_blz"
     */
    public function testPropertyCounterpartBlz()
    {
    }

    /**
     * Test attribute "counterpart_bic"
     */
    public function testPropertyCounterpartBic()
    {
    }

    /**
     * Test attribute "counterpart_bank_name"
     */
    public function testPropertyCounterpartBankName()
    {
    }

    /**
     * Test attribute "counterpart_mandate_reference"
     */
    public function testPropertyCounterpartMandateReference()
    {
    }

    /**
     * Test attribute "counterpart_customer_reference"
     */
    public function testPropertyCounterpartCustomerReference()
    {
    }

    /**
     * Test attribute "counterpart_creditor_id"
     */
    public function testPropertyCounterpartCreditorId()
    {
    }

    /**
     * Test attribute "counterpart_debitor_id"
     */
    public function testPropertyCounterpartDebitorId()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "type_code_zka"
     */
    public function testPropertyTypeCodeZka()
    {
    }

    /**
     * Test attribute "type_code_swift"
     */
    public function testPropertyTypeCodeSwift()
    {
    }

    /**
     * Test attribute "sepa_purpose_code"
     */
    public function testPropertySepaPurposeCode()
    {
    }

    /**
     * Test attribute "primanota"
     */
    public function testPropertyPrimanota()
    {
    }

    /**
     * Test attribute "category"
     */
    public function testPropertyCategory()
    {
    }

    /**
     * Test attribute "labels"
     */
    public function testPropertyLabels()
    {
    }

    /**
     * Test attribute "is_potential_duplicate"
     */
    public function testPropertyIsPotentialDuplicate()
    {
    }

    /**
     * Test attribute "is_adjusting_entry"
     */
    public function testPropertyIsAdjustingEntry()
    {
    }

    /**
     * Test attribute "is_new"
     */
    public function testPropertyIsNew()
    {
    }

    /**
     * Test attribute "import_date"
     */
    public function testPropertyImportDate()
    {
    }

    /**
     * Test attribute "children"
     */
    public function testPropertyChildren()
    {
    }

    /**
     * Test attribute "paypal_data"
     */
    public function testPropertyPaypalData()
    {
    }

    /**
     * Test attribute "end_to_end_reference"
     */
    public function testPropertyEndToEndReference()
    {
    }

    /**
     * Test attribute "compensation_amount"
     */
    public function testPropertyCompensationAmount()
    {
    }

    /**
     * Test attribute "original_amount"
     */
    public function testPropertyOriginalAmount()
    {
    }

    /**
     * Test attribute "different_debitor"
     */
    public function testPropertyDifferentDebitor()
    {
    }

    /**
     * Test attribute "different_creditor"
     */
    public function testPropertyDifferentCreditor()
    {
    }
}
