<?php
/**
 * UpdateTransactionsParamsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * finAPI RESTful Services
 *
 * finAPI RESTful Services
 *
 * OpenAPI spec version: v1.81.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * UpdateTransactionsParamsTest Class Doc Comment
 *
 * @category    Class
 * @description Update transactions parameters
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class UpdateTransactionsParamsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "UpdateTransactionsParams"
     */
    public function testUpdateTransactionsParams()
    {
    }

    /**
     * Test attribute "is_new"
     */
    public function testPropertyIsNew()
    {
    }

    /**
     * Test attribute "is_potential_duplicate"
     */
    public function testPropertyIsPotentialDuplicate()
    {
    }

    /**
     * Test attribute "category_id"
     */
    public function testPropertyCategoryId()
    {
    }

    /**
     * Test attribute "train_categorization"
     */
    public function testPropertyTrainCategorization()
    {
    }

    /**
     * Test attribute "label_ids"
     */
    public function testPropertyLabelIds()
    {
    }
}
