<?php
/**
 * UpdateBankConnectionParamsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * finAPI RESTful Services
 *
 * finAPI RESTful Services
 *
 * OpenAPI spec version: v1.81.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * UpdateBankConnectionParamsTest Class Doc Comment
 *
 * @category    Class
 * @description Container for bank connection update parameters
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class UpdateBankConnectionParamsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "UpdateBankConnectionParams"
     */
    public function testUpdateBankConnectionParams()
    {
    }

    /**
     * Test attribute "bank_connection_id"
     */
    public function testPropertyBankConnectionId()
    {
    }

    /**
     * Test attribute "banking_pin"
     */
    public function testPropertyBankingPin()
    {
    }

    /**
     * Test attribute "store_pin"
     */
    public function testPropertyStorePin()
    {
    }

    /**
     * Test attribute "interface"
     */
    public function testPropertyInterface()
    {
    }

    /**
     * Test attribute "login_credentials"
     */
    public function testPropertyLoginCredentials()
    {
    }

    /**
     * Test attribute "store_secrets"
     */
    public function testPropertyStoreSecrets()
    {
    }

    /**
     * Test attribute "import_new_accounts"
     */
    public function testPropertyImportNewAccounts()
    {
    }

    /**
     * Test attribute "skip_positions_download"
     */
    public function testPropertySkipPositionsDownload()
    {
    }

    /**
     * Test attribute "load_owner_data"
     */
    public function testPropertyLoadOwnerData()
    {
    }

    /**
     * Test attribute "account_references"
     */
    public function testPropertyAccountReferences()
    {
    }

    /**
     * Test attribute "challenge_response"
     */
    public function testPropertyChallengeResponse()
    {
    }

    /**
     * Test attribute "multi_step_authentication"
     */
    public function testPropertyMultiStepAuthentication()
    {
    }

    /**
     * Test attribute "redirect_url"
     */
    public function testPropertyRedirectUrl()
    {
    }
}
