<?php
/**
 * BankTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * finAPI RESTful Services
 *
 * finAPI RESTful Services
 *
 * OpenAPI spec version: v1.81.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * BankTest Class Doc Comment
 *
 * @category    Class
 * @description Container for a bank&#39;s data
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BankTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Bank"
     */
    public function testBank()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "login_hint"
     */
    public function testPropertyLoginHint()
    {
    }

    /**
     * Test attribute "bic"
     */
    public function testPropertyBic()
    {
    }

    /**
     * Test attribute "blzs"
     */
    public function testPropertyBlzs()
    {
    }

    /**
     * Test attribute "blz"
     */
    public function testPropertyBlz()
    {
    }

    /**
     * Test attribute "location"
     */
    public function testPropertyLocation()
    {
    }

    /**
     * Test attribute "city"
     */
    public function testPropertyCity()
    {
    }

    /**
     * Test attribute "is_supported"
     */
    public function testPropertyIsSupported()
    {
    }

    /**
     * Test attribute "is_test_bank"
     */
    public function testPropertyIsTestBank()
    {
    }

    /**
     * Test attribute "popularity"
     */
    public function testPropertyPopularity()
    {
    }

    /**
     * Test attribute "health"
     */
    public function testPropertyHealth()
    {
    }

    /**
     * Test attribute "login_field_user_id"
     */
    public function testPropertyLoginFieldUserId()
    {
    }

    /**
     * Test attribute "login_field_customer_id"
     */
    public function testPropertyLoginFieldCustomerId()
    {
    }

    /**
     * Test attribute "login_field_pin"
     */
    public function testPropertyLoginFieldPin()
    {
    }

    /**
     * Test attribute "pins_are_volatile"
     */
    public function testPropertyPinsAreVolatile()
    {
    }

    /**
     * Test attribute "is_customer_id_password"
     */
    public function testPropertyIsCustomerIdPassword()
    {
    }

    /**
     * Test attribute "supported_data_sources"
     */
    public function testPropertySupportedDataSources()
    {
    }

    /**
     * Test attribute "interfaces"
     */
    public function testPropertyInterfaces()
    {
    }

    /**
     * Test attribute "last_communication_attempt"
     */
    public function testPropertyLastCommunicationAttempt()
    {
    }

    /**
     * Test attribute "last_successful_communication"
     */
    public function testPropertyLastSuccessfulCommunication()
    {
    }
}
