<?php
/**
 * BankConnectionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * finAPI RESTful Services
 *
 * finAPI RESTful Services
 *
 * OpenAPI spec version: v1.81.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * BankConnectionTest Class Doc Comment
 *
 * @category    Class
 * @description Container for a bank connection&#39;s data
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BankConnectionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "BankConnection"
     */
    public function testBankConnection()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "bank_id"
     */
    public function testPropertyBankId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "banking_user_id"
     */
    public function testPropertyBankingUserId()
    {
    }

    /**
     * Test attribute "banking_customer_id"
     */
    public function testPropertyBankingCustomerId()
    {
    }

    /**
     * Test attribute "banking_pin"
     */
    public function testPropertyBankingPin()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "update_status"
     */
    public function testPropertyUpdateStatus()
    {
    }

    /**
     * Test attribute "categorization_status"
     */
    public function testPropertyCategorizationStatus()
    {
    }

    /**
     * Test attribute "last_manual_update"
     */
    public function testPropertyLastManualUpdate()
    {
    }

    /**
     * Test attribute "last_auto_update"
     */
    public function testPropertyLastAutoUpdate()
    {
    }

    /**
     * Test attribute "iban_only_money_transfer_supported"
     */
    public function testPropertyIbanOnlyMoneyTransferSupported()
    {
    }

    /**
     * Test attribute "iban_only_direct_debit_supported"
     */
    public function testPropertyIbanOnlyDirectDebitSupported()
    {
    }

    /**
     * Test attribute "collective_money_transfer_supported"
     */
    public function testPropertyCollectiveMoneyTransferSupported()
    {
    }

    /**
     * Test attribute "default_two_step_procedure_id"
     */
    public function testPropertyDefaultTwoStepProcedureId()
    {
    }

    /**
     * Test attribute "two_step_procedures"
     */
    public function testPropertyTwoStepProcedures()
    {
    }

    /**
     * Test attribute "interfaces"
     */
    public function testPropertyInterfaces()
    {
    }

    /**
     * Test attribute "account_ids"
     */
    public function testPropertyAccountIds()
    {
    }

    /**
     * Test attribute "owners"
     */
    public function testPropertyOwners()
    {
    }

    /**
     * Test attribute "bank"
     */
    public function testPropertyBank()
    {
    }

    /**
     * Test attribute "further_login_not_recommended"
     */
    public function testPropertyFurtherLoginNotRecommended()
    {
    }
}
