<?php
/**
 * BankConnectionInterfaceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * finAPI RESTful Services
 *
 * finAPI RESTful Services
 *
 * OpenAPI spec version: v1.81.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * BankConnectionInterfaceTest Class Doc Comment
 *
 * @category    Class
 * @description Resource representing a bank connection interface
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BankConnectionInterfaceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "BankConnectionInterface"
     */
    public function testBankConnectionInterface()
    {
    }

    /**
     * Test attribute "interface"
     */
    public function testPropertyInterface()
    {
    }

    /**
     * Test attribute "login_credentials"
     */
    public function testPropertyLoginCredentials()
    {
    }

    /**
     * Test attribute "default_two_step_procedure_id"
     */
    public function testPropertyDefaultTwoStepProcedureId()
    {
    }

    /**
     * Test attribute "two_step_procedures"
     */
    public function testPropertyTwoStepProcedures()
    {
    }

    /**
     * Test attribute "ais_consent"
     */
    public function testPropertyAisConsent()
    {
    }

    /**
     * Test attribute "last_manual_update"
     */
    public function testPropertyLastManualUpdate()
    {
    }

    /**
     * Test attribute "last_auto_update"
     */
    public function testPropertyLastAutoUpdate()
    {
    }
}
