<?php
/**
 * CashFlowListTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * finAPI RESTful Services
 *
 * finAPI RESTful Services
 *
 * OpenAPI spec version: v1.81.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CashFlowListTest Class Doc Comment
 *
 * @category    Class
 * @description Cash flows
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CashFlowListTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CashFlowList"
     */
    public function testCashFlowList()
    {
    }

    /**
     * Test attribute "cash_flows"
     */
    public function testPropertyCashFlows()
    {
    }

    /**
     * Test attribute "total_income"
     */
    public function testPropertyTotalIncome()
    {
    }

    /**
     * Test attribute "total_spending"
     */
    public function testPropertyTotalSpending()
    {
    }

    /**
     * Test attribute "total_balance"
     */
    public function testPropertyTotalBalance()
    {
    }
}
