<?php
/**
 * ClientConfigurationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * finAPI RESTful Services
 *
 * finAPI RESTful Services
 *
 * OpenAPI spec version: v1.81.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ClientConfigurationTest Class Doc Comment
 *
 * @category    Class
 * @description Client configuration parameters
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ClientConfigurationTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ClientConfiguration"
     */
    public function testClientConfiguration()
    {
    }

    /**
     * Test attribute "is_automatic_batch_update_enabled"
     */
    public function testPropertyIsAutomaticBatchUpdateEnabled()
    {
    }

    /**
     * Test attribute "user_notification_callback_url"
     */
    public function testPropertyUserNotificationCallbackUrl()
    {
    }

    /**
     * Test attribute "user_synchronization_callback_url"
     */
    public function testPropertyUserSynchronizationCallbackUrl()
    {
    }

    /**
     * Test attribute "refresh_tokens_validity_period"
     */
    public function testPropertyRefreshTokensValidityPeriod()
    {
    }

    /**
     * Test attribute "user_access_tokens_validity_period"
     */
    public function testPropertyUserAccessTokensValidityPeriod()
    {
    }

    /**
     * Test attribute "client_access_tokens_validity_period"
     */
    public function testPropertyClientAccessTokensValidityPeriod()
    {
    }

    /**
     * Test attribute "max_user_login_attempts"
     */
    public function testPropertyMaxUserLoginAttempts()
    {
    }

    /**
     * Test attribute "is_user_auto_verification_enabled"
     */
    public function testPropertyIsUserAutoVerificationEnabled()
    {
    }

    /**
     * Test attribute "is_mandator_admin"
     */
    public function testPropertyIsMandatorAdmin()
    {
    }

    /**
     * Test attribute "is_web_scraping_enabled"
     */
    public function testPropertyIsWebScrapingEnabled()
    {
    }

    /**
     * Test attribute "is_xs2a_enabled"
     */
    public function testPropertyIsXs2aEnabled()
    {
    }

    /**
     * Test attribute "available_bank_groups"
     */
    public function testPropertyAvailableBankGroups()
    {
    }

    /**
     * Test attribute "application_name"
     */
    public function testPropertyApplicationName()
    {
    }

    /**
     * Test attribute "fin_ts_product_registration_number"
     */
    public function testPropertyFinTsProductRegistrationNumber()
    {
    }

    /**
     * Test attribute "store_secrets_available_in_web_form"
     */
    public function testPropertyStoreSecretsAvailableInWebForm()
    {
    }

    /**
     * Test attribute "payments_enabled"
     */
    public function testPropertyPaymentsEnabled()
    {
    }

    /**
     * Test attribute "pin_storage_available_in_web_form"
     */
    public function testPropertyPinStorageAvailableInWebForm()
    {
    }
}
