<?php
/**
 * NewTransactionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * finAPI RESTful Services
 *
 * finAPI RESTful Services
 *
 * OpenAPI spec version: v1.81.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * NewTransactionTest Class Doc Comment
 *
 * @category    Class
 * @description Mock transaction data
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class NewTransactionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "NewTransaction"
     */
    public function testNewTransaction()
    {
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
    }

    /**
     * Test attribute "purpose"
     */
    public function testPropertyPurpose()
    {
    }

    /**
     * Test attribute "counterpart"
     */
    public function testPropertyCounterpart()
    {
    }

    /**
     * Test attribute "counterpart_iban"
     */
    public function testPropertyCounterpartIban()
    {
    }

    /**
     * Test attribute "counterpart_blz"
     */
    public function testPropertyCounterpartBlz()
    {
    }

    /**
     * Test attribute "counterpart_bic"
     */
    public function testPropertyCounterpartBic()
    {
    }

    /**
     * Test attribute "counterpart_account_number"
     */
    public function testPropertyCounterpartAccountNumber()
    {
    }

    /**
     * Test attribute "booking_date"
     */
    public function testPropertyBookingDate()
    {
    }

    /**
     * Test attribute "value_date"
     */
    public function testPropertyValueDate()
    {
    }
}
