<?php
/**
 * RequestSepaMoneyTransferParamsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * finAPI RESTful Services
 *
 * finAPI RESTful Services
 *
 * OpenAPI spec version: v1.81.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * RequestSepaMoneyTransferParamsTest Class Doc Comment
 *
 * @category    Class
 * @description Parameters for a single or collective SEPA money transfer order request
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RequestSepaMoneyTransferParamsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "RequestSepaMoneyTransferParams"
     */
    public function testRequestSepaMoneyTransferParams()
    {
    }

    /**
     * Test attribute "recipient_name"
     */
    public function testPropertyRecipientName()
    {
    }

    /**
     * Test attribute "recipient_iban"
     */
    public function testPropertyRecipientIban()
    {
    }

    /**
     * Test attribute "recipient_bic"
     */
    public function testPropertyRecipientBic()
    {
    }

    /**
     * Test attribute "clearing_account_id"
     */
    public function testPropertyClearingAccountId()
    {
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
    }

    /**
     * Test attribute "purpose"
     */
    public function testPropertyPurpose()
    {
    }

    /**
     * Test attribute "sepa_purpose_code"
     */
    public function testPropertySepaPurposeCode()
    {
    }

    /**
     * Test attribute "account_id"
     */
    public function testPropertyAccountId()
    {
    }

    /**
     * Test attribute "banking_pin"
     */
    public function testPropertyBankingPin()
    {
    }

    /**
     * Test attribute "store_secrets"
     */
    public function testPropertyStoreSecrets()
    {
    }

    /**
     * Test attribute "two_step_procedure_id"
     */
    public function testPropertyTwoStepProcedureId()
    {
    }

    /**
     * Test attribute "execution_date"
     */
    public function testPropertyExecutionDate()
    {
    }

    /**
     * Test attribute "single_booking"
     */
    public function testPropertySingleBooking()
    {
    }

    /**
     * Test attribute "additional_money_transfers"
     */
    public function testPropertyAdditionalMoneyTransfers()
    {
    }

    /**
     * Test attribute "challenge_response"
     */
    public function testPropertyChallengeResponse()
    {
    }

    /**
     * Test attribute "multi_step_authentication"
     */
    public function testPropertyMultiStepAuthentication()
    {
    }

    /**
     * Test attribute "hide_transaction_details_in_web_form"
     */
    public function testPropertyHideTransactionDetailsInWebForm()
    {
    }

    /**
     * Test attribute "store_pin"
     */
    public function testPropertyStorePin()
    {
    }
}
