<?php
/**
 * SingleDirectDebitDataTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * finAPI RESTful Services
 *
 * finAPI RESTful Services
 *
 * OpenAPI spec version: v1.81.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * SingleDirectDebitDataTest Class Doc Comment
 *
 * @category    Class
 * @description Data for a single direct debit
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SingleDirectDebitDataTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SingleDirectDebitData"
     */
    public function testSingleDirectDebitData()
    {
    }

    /**
     * Test attribute "debitor_name"
     */
    public function testPropertyDebitorName()
    {
    }

    /**
     * Test attribute "debitor_iban"
     */
    public function testPropertyDebitorIban()
    {
    }

    /**
     * Test attribute "debitor_bic"
     */
    public function testPropertyDebitorBic()
    {
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
    }

    /**
     * Test attribute "purpose"
     */
    public function testPropertyPurpose()
    {
    }

    /**
     * Test attribute "sepa_purpose_code"
     */
    public function testPropertySepaPurposeCode()
    {
    }

    /**
     * Test attribute "mandate_id"
     */
    public function testPropertyMandateId()
    {
    }

    /**
     * Test attribute "mandate_date"
     */
    public function testPropertyMandateDate()
    {
    }

    /**
     * Test attribute "creditor_id"
     */
    public function testPropertyCreditorId()
    {
    }

    /**
     * Test attribute "end_to_end_id"
     */
    public function testPropertyEndToEndId()
    {
    }
}
