<?php
/**
 * TppCredentialsParamsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * finAPI RESTful Services
 *
 * finAPI RESTful Services
 *
 * OpenAPI spec version: v1.81.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * TppCredentialsParamsTest Class Doc Comment
 *
 * @category    Class
 * @description A container for new TPP client credentials data
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TppCredentialsParamsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "TppCredentialsParams"
     */
    public function testTppCredentialsParams()
    {
    }

    /**
     * Test attribute "tpp_authentication_group_id"
     */
    public function testPropertyTppAuthenticationGroupId()
    {
    }

    /**
     * Test attribute "label"
     */
    public function testPropertyLabel()
    {
    }

    /**
     * Test attribute "tpp_client_id"
     */
    public function testPropertyTppClientId()
    {
    }

    /**
     * Test attribute "tpp_client_secret"
     */
    public function testPropertyTppClientSecret()
    {
    }

    /**
     * Test attribute "tpp_api_key"
     */
    public function testPropertyTppApiKey()
    {
    }

    /**
     * Test attribute "valid_from_date"
     */
    public function testPropertyValidFromDate()
    {
    }

    /**
     * Test attribute "valid_until_date"
     */
    public function testPropertyValidUntilDate()
    {
    }
}
