<?php
/**
 * TppCertificateParamsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * finAPI RESTful Services
 *
 * finAPI RESTful Services
 *
 * OpenAPI spec version: v1.81.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * TppCertificateParamsTest Class Doc Comment
 *
 * @category    Class
 * @description A container for the new certificate data
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TppCertificateParamsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "TppCertificateParams"
     */
    public function testTppCertificateParams()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "public_key"
     */
    public function testPropertyPublicKey()
    {
    }

    /**
     * Test attribute "private_key"
     */
    public function testPropertyPrivateKey()
    {
    }

    /**
     * Test attribute "passphrase"
     */
    public function testPropertyPassphrase()
    {
    }

    /**
     * Test attribute "label"
     */
    public function testPropertyLabel()
    {
    }

    /**
     * Test attribute "valid_from_date"
     */
    public function testPropertyValidFromDate()
    {
    }

    /**
     * Test attribute "valid_until_date"
     */
    public function testPropertyValidUntilDate()
    {
    }
}
