<?php
/**
 * TwoStepProcedureTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * finAPI RESTful Services
 *
 * finAPI RESTful Services
 *
 * OpenAPI spec version: v1.81.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * TwoStepProcedureTest Class Doc Comment
 *
 * @category    Class
 * @description Two-step-procedure for user authorization on bank-side
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TwoStepProcedureTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "TwoStepProcedure"
     */
    public function testTwoStepProcedure()
    {
    }

    /**
     * Test attribute "procedure_id"
     */
    public function testPropertyProcedureId()
    {
    }

    /**
     * Test attribute "procedure_name"
     */
    public function testPropertyProcedureName()
    {
    }

    /**
     * Test attribute "procedure_challenge_type"
     */
    public function testPropertyProcedureChallengeType()
    {
    }

    /**
     * Test attribute "implicit_execute"
     */
    public function testPropertyImplicitExecute()
    {
    }
}
