<?php
/**
 * UserInfoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * finAPI RESTful Services
 *
 * finAPI RESTful Services
 *
 * OpenAPI spec version: v1.81.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * UserInfoTest Class Doc Comment
 *
 * @category    Class
 * @description Container for user information
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class UserInfoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "UserInfo"
     */
    public function testUserInfo()
    {
    }

    /**
     * Test attribute "user_id"
     */
    public function testPropertyUserId()
    {
    }

    /**
     * Test attribute "registration_date"
     */
    public function testPropertyRegistrationDate()
    {
    }

    /**
     * Test attribute "deletion_date"
     */
    public function testPropertyDeletionDate()
    {
    }

    /**
     * Test attribute "last_active_date"
     */
    public function testPropertyLastActiveDate()
    {
    }

    /**
     * Test attribute "bank_connection_count"
     */
    public function testPropertyBankConnectionCount()
    {
    }

    /**
     * Test attribute "latest_bank_connection_import_date"
     */
    public function testPropertyLatestBankConnectionImportDate()
    {
    }

    /**
     * Test attribute "latest_bank_connection_deletion_date"
     */
    public function testPropertyLatestBankConnectionDeletionDate()
    {
    }

    /**
     * Test attribute "monthly_stats"
     */
    public function testPropertyMonthlyStats()
    {
    }

    /**
     * Test attribute "is_locked"
     */
    public function testPropertyIsLocked()
    {
    }
}
