<?php
/**
 * AccountsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * finAPI RESTful Services
 *
 * finAPI RESTful Services
 *
 * OpenAPI spec version: v1.81.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * AccountsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AccountsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for deleteAccount
     *
     * Delete an account.
     *
     */
    public function testDeleteAccount()
    {
    }

    /**
     * Test case for deleteAllAccounts
     *
     * Delete all accounts.
     *
     */
    public function testDeleteAllAccounts()
    {
    }

    /**
     * Test case for editAccount
     *
     * Edit an account.
     *
     */
    public function testEditAccount()
    {
    }

    /**
     * Test case for executeSepaDirectDebit
     *
     * Execute SEPA Direct Debit.
     *
     */
    public function testExecuteSepaDirectDebit()
    {
    }

    /**
     * Test case for executeSepaMoneyTransfer
     *
     * Execute SEPA Money Transfer.
     *
     */
    public function testExecuteSepaMoneyTransfer()
    {
    }

    /**
     * Test case for getAccount
     *
     * Get an account.
     *
     */
    public function testGetAccount()
    {
    }

    /**
     * Test case for getAndSearchAllAccounts
     *
     * Get and search all accounts.
     *
     */
    public function testGetAndSearchAllAccounts()
    {
    }

    /**
     * Test case for getDailyBalances
     *
     * Get daily balances.
     *
     */
    public function testGetDailyBalances()
    {
    }

    /**
     * Test case for getMultipleAccounts
     *
     * Get multiple accounts.
     *
     */
    public function testGetMultipleAccounts()
    {
    }

    /**
     * Test case for requestSepaDirectDebit
     *
     * Request SEPA Direct Debit.
     *
     */
    public function testRequestSepaDirectDebit()
    {
    }

    /**
     * Test case for requestSepaMoneyTransfer
     *
     * Request SEPA Money Transfer.
     *
     */
    public function testRequestSepaMoneyTransfer()
    {
    }
}
