<?php
/**
 * BankConnectionsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * finAPI RESTful Services
 *
 * finAPI RESTful Services
 *
 * OpenAPI spec version: v1.81.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * BankConnectionsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class BankConnectionsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for connectInterface
     *
     * Connect a new interface.
     *
     */
    public function testConnectInterface()
    {
    }

    /**
     * Test case for deleteAllBankConnections
     *
     * Delete all bank connections.
     *
     */
    public function testDeleteAllBankConnections()
    {
    }

    /**
     * Test case for deleteBankConnection
     *
     * Delete a bank connection.
     *
     */
    public function testDeleteBankConnection()
    {
    }

    /**
     * Test case for editBankConnection
     *
     * Edit a bank connection.
     *
     */
    public function testEditBankConnection()
    {
    }

    /**
     * Test case for getAllBankConnections
     *
     * Get all bank connections.
     *
     */
    public function testGetAllBankConnections()
    {
    }

    /**
     * Test case for getBankConnection
     *
     * Get a bank connection.
     *
     */
    public function testGetBankConnection()
    {
    }

    /**
     * Test case for getMultipleBankConnections
     *
     * Get multiple bank connections.
     *
     */
    public function testGetMultipleBankConnections()
    {
    }

    /**
     * Test case for importBankConnection
     *
     * Import a new bank connection.
     *
     */
    public function testImportBankConnection()
    {
    }

    /**
     * Test case for removeInterface
     *
     * Remove an interface.
     *
     */
    public function testRemoveInterface()
    {
    }

    /**
     * Test case for updateBankConnection
     *
     * Update a bank connection.
     *
     */
    public function testUpdateBankConnection()
    {
    }
}
