<?php
/**
 * TPPCredentialsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * finAPI RESTful Services
 *
 * finAPI RESTful Services
 *
 * OpenAPI spec version: v1.81.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * TPPCredentialsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TPPCredentialsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createTppCredential
     *
     * Create new TPP credentials.
     *
     */
    public function testCreateTppCredential()
    {
    }

    /**
     * Test case for deleteTppCredential
     *
     * Delete a set of TPP credentials.
     *
     */
    public function testDeleteTppCredential()
    {
    }

    /**
     * Test case for editTppCredential
     *
     * Edit a set of TPP credentials.
     *
     */
    public function testEditTppCredential()
    {
    }

    /**
     * Test case for getAllTppCredentials
     *
     * Get all TPP credentials.
     *
     */
    public function testGetAllTppCredentials()
    {
    }

    /**
     * Test case for getAndSearchTppAuthenticationGroups
     *
     * Get all TPP Authentication Groups.
     *
     */
    public function testGetAndSearchTppAuthenticationGroups()
    {
    }

    /**
     * Test case for getTppCredential
     *
     * Get a set of TPP credentials.
     *
     */
    public function testGetTppCredential()
    {
    }
}
