<?php
/**
 * TransactionsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * finAPI RESTful Services
 *
 * finAPI RESTful Services
 *
 * OpenAPI spec version: v1.81.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * TransactionsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TransactionsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for deleteAllTransactions
     *
     * Delete all transactions.
     *
     */
    public function testDeleteAllTransactions()
    {
    }

    /**
     * Test case for deleteTransaction
     *
     * Delete a transaction.
     *
     */
    public function testDeleteTransaction()
    {
    }

    /**
     * Test case for editMultipleTransactions
     *
     * Edit multiple transactions.
     *
     */
    public function testEditMultipleTransactions()
    {
    }

    /**
     * Test case for editMultipleTransactionsDeprecated
     *
     * Edit multiple transactions (DEPRECATED).
     *
     */
    public function testEditMultipleTransactionsDeprecated()
    {
    }

    /**
     * Test case for editTransaction
     *
     * Edit a transaction.
     *
     */
    public function testEditTransaction()
    {
    }

    /**
     * Test case for getAndSearchAllTransactions
     *
     * Get and search all transactions.
     *
     */
    public function testGetAndSearchAllTransactions()
    {
    }

    /**
     * Test case for getMultipleTransactions
     *
     * Get multiple transactions.
     *
     */
    public function testGetMultipleTransactions()
    {
    }

    /**
     * Test case for getTransaction
     *
     * Get a transaction.
     *
     */
    public function testGetTransaction()
    {
    }

    /**
     * Test case for restoreTransaction
     *
     * Restore a transaction.
     *
     */
    public function testRestoreTransaction()
    {
    }

    /**
     * Test case for splitTransaction
     *
     * Split a transaction.
     *
     */
    public function testSplitTransaction()
    {
    }

    /**
     * Test case for triggerCategorization
     *
     * Trigger categorization.
     *
     */
    public function testTriggerCategorization()
    {
    }
}
