<?php
/**
 * UsersApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * finAPI RESTful Services
 *
 * finAPI RESTful Services
 *
 * OpenAPI spec version: v1.81.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * UsersApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class UsersApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createUser
     *
     * Create a new user.
     *
     */
    public function testCreateUser()
    {
    }

    /**
     * Test case for deleteAuthorizedUser
     *
     * Delete the authorized user.
     *
     */
    public function testDeleteAuthorizedUser()
    {
    }

    /**
     * Test case for deleteUnverifiedUser
     *
     * Delete an unverified user.
     *
     */
    public function testDeleteUnverifiedUser()
    {
    }

    /**
     * Test case for editAuthorizedUser
     *
     * Edit the authorized user.
     *
     */
    public function testEditAuthorizedUser()
    {
    }

    /**
     * Test case for executePasswordChange
     *
     * Execute password change.
     *
     */
    public function testExecutePasswordChange()
    {
    }

    /**
     * Test case for getAuthorizedUser
     *
     * Get the authorized user.
     *
     */
    public function testGetAuthorizedUser()
    {
    }

    /**
     * Test case for getVerificationStatus
     *
     * Get a user's verification status.
     *
     */
    public function testGetVerificationStatus()
    {
    }

    /**
     * Test case for requestPasswordChange
     *
     * Request password change.
     *
     */
    public function testRequestPasswordChange()
    {
    }

    /**
     * Test case for verifyUser
     *
     * Verify a user.
     *
     */
    public function testVerifyUser()
    {
    }
}
